services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-bookshelf-app
    image: laravel-book-shelf-app:latest
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    environment:
      - DB_CONNECTION=sqlite
    networks:
      - bookshelf

  nginx:
    image: nginx:alpine
    container_name: laravel-bookshelf-nginx
    restart: unless-stopped
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - bookshelf

  # Optional for development environment
  npm:
    image: node:20-slim
    container_name: laravel-bookshelf-npm
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    profiles: ['dev']
    entrypoint: ['npm']
    command: ['run', 'dev', '--', '--host', '0.0.0.0']
    ports:
      - '5173:5173'
    networks:
      - bookshelf

networks:
  bookshelf:
    driver: bridge

volumes:
  dbdata:
    driver: local
