version: '3.8'

services:
  # Laravel Application
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: laravel-bookshelf-app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    networks:
      - bookshelf

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: laravel-bookshelf-nginx
    restart: unless-stopped
    ports:
      # Production configuration with port 80 for domain access
      - '80:80'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - bookshelf

  # Node.js Development Server
  node:
    image: node:21-alpine
    container_name: laravel-bookshelf-node
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - '5173:5173'
    networks:
      - bookshelf

  # Build frontend assets for production
  build-frontend:
    image: node:20-slim
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run build"
    profiles:
      - build

networks:
  bookshelf:
    driver: bridge
