name: AWS Deployment

on:
  push:
    branches: [ci-cd]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker images
        run: |
          # Build the app service with --no-cache to ensure fresh build
          docker compose build --progress=plain --no-cache app

          # Get the image ID from the built image
          IMAGE_ID=$(docker images -q laravel-book-shelf-app:latest)

          # Tag with both latest and commit hash
          docker tag $IMAGE_ID ${{ secrets.AWS_ECR_REPO_URI }}:latest
          docker tag $IMAGE_ID ${{ secrets.AWS_ECR_REPO_URI }}:${{ github.sha }}

      - name: Push to Amazon ECR
        run: |
          # Push both tags to ECR
          docker push ${{ secrets.AWS_ECR_REPO_URI }}:latest
          docker push ${{ secrets.AWS_ECR_REPO_URI }}:${{ github.sha }}

      - name: Deploy to AWS ECS
        run: |
          aws ecs update-service \
            --cluster ${{ secrets.AWS_ECS_CLUSTER }} \
            --service ${{ secrets.AWS_ECS_SERVICE }} \
            --force-new-deployment \
            --region ${{ secrets.AWS_REGION }}
