name: AWS CI/CD Pipeline

on:
  push:
    branches: [main, ci-cd]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker images
        run: |
          # Build the app service with --no-cache to ensure fresh build
          docker compose build --progress=plain --no-cache app

          # Get the image ID from the built image
          IMAGE_ID=$(docker images -q laravel-book-shelf-app:latest)
          echo "Built image ID: $IMAGE_ID"

          # Tag with both latest and commit hash
          docker tag $IMAGE_ID ${{ secrets.AWS_ECR_REPO_URI }}:latest
          docker tag $IMAGE_ID ${{ secrets.AWS_ECR_REPO_URI }}:${{ github.sha }}
          echo "Tagged images with latest and ${{ github.sha }}"

      - name: Push to Amazon ECR
        run: |
          # Push both tags to ECR
          docker push ${{ secrets.AWS_ECR_REPO_URI }}:latest
          docker push ${{ secrets.AWS_ECR_REPO_URI }}:${{ github.sha }}
          echo "Pushed images to ECR: ${{ secrets.AWS_ECR_REPO_URI }}:latest and ${{ secrets.AWS_ECR_REPO_URI }}:${{ github.sha }}"

      - name: Download task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition ${{ secrets.AWS_ECS_TASK_DEFINITION }} \
            --query taskDefinition > task-definition.json
          echo "Downloaded current task definition"

      - name: Update container image in task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: laravel-app
          image: ${{ secrets.AWS_ECR_REPO_URI }}:${{ github.sha }}

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ secrets.AWS_ECS_SERVICE }}
          cluster: ${{ secrets.AWS_ECS_CLUSTER }}
          wait-for-service-stability: true
