name: AWS Deployment

on:
  push:
    branches: [ci-cd]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker images
        run: |
          docker compose build --progress=plain app

          IMAGE_ID=$(docker images -q app:latest)

          # docker tag $IMAGE_ID ${{ secrets.AWS_ECR_REPO_URI }}:latest
          # docker tag $IMAGE_ID ${{ secrets.AWS_ECR_REPO_URI }}:${{ github.sha }}
          # docker push ${{ secrets.AWS_ECR_REPO_URI }}:latest
          # docker push ${{ secrets.AWS_ECR_REPO_URI }}:${{ github.sha }}
